### ISSUE TITLE
Use :global t for gif-screencast-mode?

### ISSUE THREAD

**Issue by proofit404** [Ambrevar/emacs-gif-screencast#3]
Hi, thanks for this project! It appears at the very right time in my life :+1: 

Suggested change should make `F9` buttons work even if I decide to stop recording inside another buffer.

Regards, Artem.

**Comment by Ambrevar** [comment]
Right, this got fixed in #2.  Thanks for reporting!

**Comment by proofit404** [comment]
Thanks!
