### ISSUE TITLE
Error report from package-lint.el

### ISSUE THREAD

**Issue by takaxp** [Ambrevar/emacs-gif-screencast#7]
package-lint.el reports 2 warnings and 1 error.

138:62: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
139:54: warning: This key sequence is reserved (see Key Binding Conventions in the Emacs Lisp manual)
143:0: error: Global minor modes must `:require' their defining file (i.e. ":require 'gif-screencast"), to support the customization variable of the same name.

I believe at least the error should be resolved.

**Comment by Ambrevar** [comment]
Indeed, that just got introduced.

Regarding the warnings: I know about them but I can't think of good bindings.  Suggestions are welcome.

**Comment by takaxp** [comment]
IMO, for the key bindings, just make them open to users but a recommend setting should be described in README explicitly. I had the same issue on [org-tree-slide](https://github.com/takaxp/org-tree-slide) then I assigned non-reserved keys.

**Comment by Ambrevar** [comment]
Sounds reasonable.

**Comment by Ambrevar** [comment]
Fixed in 9aa921e0d991d4920a84f5eea1b7ab00424e5241 and df05e26c54e5cf4054e39448aa47130a57d63987.
